### ISSUE TITLE
[macos : show battery %] Type mismatch. Type in defaults: str

### ISSUE THREAD

**Issue by glevine** [glevine/machine#5]
```
TASK [macos : show battery %] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {“changed”: false, “msg”: “Type mismatch. Type in defaults: str”}
```

Appears to be related to https://github.com/ansible/ansible/issues/29404. I believe the user had already set the show battery % setting using the UI and it was set using a string instead of a boolean.

Need to figure out what the proper string is. Maybe it is `YES` (https://www.jamf.com/jamf-nation/discussions/20794/enabling-show-battery-percentage-via-script-or-policy).

**Comment by elisiano** [comment]
I fixed this by changing the `osx_defaults`' `type` from `boolean` to `string`

**Comment by glevine** [comment]
No longer appears to be an issue. Likely resolved by https://github.com/glevine/dotfiles/commit/14eba6adbbd5afc60893789468da8d94d2058cfe#diff-2b619e5c7c5c228b886e968419fa8db6e3b1edf59d51ec1cd983685aa4869682R76.
